### ISSUE TITLE
MS SQL Server not possible?

### ISSUE THREAD

**Issue by paphko** [IDI-Systems/SSProCloud-Docker#4]
Thank you for sharing your setup!
On Windows, I failed to mount the installer file into the container, but after I copied it manually, I could finally install the server via an RDP connection.
However, the MS SQL server is not available when adding a new database:
![image](https://user-images.githubusercontent.com/6435623/210806002-34bd6a6c-afb5-4193-a1ee-1e14f83c773e.png)

Is this the same for you?
I use the 32bit Pro Cloud Server v5.0.105.
I also ran winetricks mdac28.

Do you have any idea why I cannot configure a MS SQL server?

**Comment by jonpas** [comment]
Can confirm, Microsoft SQL Server is not available. It might be a case of missing driver (although Native DBMS should not need any external driver) or some incompatibility. I am not sure how it works in a regular installation to compare, or what the requirements are.

**Comment by paphko** [comment]
Thanks for checking this. I already asked Sparx support, waiting for response now...

**Comment by paphko** [comment]
I got a very disappointing answer:

> Thanks for contacting Sparx support.
>
> Please be informed that currently it is not possible to define a Native SQL Server connection while running in Wine. It was found that Wine did not include a number of necessary drivers that come natively in Windows and therefore to avoid issues we disabled the SQL Server option when running under Wine.
>
> If you have any further questions please let us know.

I guess we can close the issue 😞

**Comment by jonpas** [comment]
That's too bad, but understandable with it being software specifically designed to work in the native Windows ecosystem.
