### ISSUE TITLE
Connecting to Floating License Server from Enterprise Architect not possible

### ISSUE THREAD

**Issue by bxn-ts** [IDI-Systems/SSProCloud-Docker#6]
Hi,

while the process of setting up everything is very smooth (👏 ), I'm having trouble connecting to the FLS from EA.

This fails with both SSH tunnel and entering `https://localhost:1805` in the EA, but also the public IP address of the AWS EC2 instance I'm running this one. There's a security group in place that allows for tcp/1805 connections.

Any ideas what's missing? The docs from Sparx Systems were not helpful when trying to troubleshoot.

**Comment by jonpas** [comment]
Did you setup an SSL certificate?
